# Continuous Integration action

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request: 
    branches: [ '*' ]

defaults:
  run:
    working-directory: Bin

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains build jobs
  build_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Ensure MSVC tools are available
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
  
    # Generate and build MSVC project using batch file
    - name: Build using MSVC
      run: BuildMSVC.cmd

  build_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    # Generate and build MSVC project using batch file
    - name: Build using make
      run: BuildMakefiles.sh

